apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
  annotations:
    apps.3scale.net/apimanager-threescale-version: '2.13'
spec:
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: false
  system:
    appSpec:
      developerContainerResources:
        limits:
          cpu: 250m
          memory: 2500Mi
        requests:
          cpu: 50m
          memory: 600Mi
      masterContainerResources:
        limits:
          cpu: 250m
          memory: 2500Mi
        requests:
          cpu: 50m
          memory: 600Mi
      providerContainerResources:
        limits:
          cpu: 250m
          memory: 1800Mi
        requests:
          cpu: 50m
          memory: 600Mi
      replicas: 1
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
    database:
      mysql:
        persistentVolumeClaim:
          storageClassName: "gp3-csi"
          resources: 
            requests:
              storage: 2Gi
    sidekiqSpec:
      replicas: 1
    sphinxSpec: {}
  appLabel: 3scale-api-management
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
  backend:
    cronSpec:
      replicas: 1
    listenerSpec:
      replicas: 1
    workerSpec:
      replicas: 1
  tenantName: 3scale
  apicast:
    managementAPI: status
    openSSLVerify: false
    productionSpec:
      replicas: 1
    registryURL: 'http://apicast-staging:8090/policies'
    responseCodes: true
    stagingSpec:
      replicas: 1
  wildcardDomain: 3scale.apps.prod-ocp-sno.changeme.aws

