apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
  namespace: 3scale
spec:
  apicast:
    managementAPI: status
    openSSLVerify: false
    productionSpec: 
      replicas: 1
    registryURL: http://apicast-staging:8090/policies
    responseCodes: true
    stagingSpec: 
      replicas: 1
  appLabel: 3scale-api-management
  backend:
    cronSpec: 
      replicas: 1
    listenerSpec: 
      replicas: 1
    workerSpec: 
      replicas: 1
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: false
  system:
    appSpec: 
      replicas: 1
#    fileStorage:
#      simpleStorageService:
#        configurationSecretRef:
#          name: aws-auth
    sidekiqSpec: 
      replicas: 1
    sphinxSpec: 
      replicas: 1
  zync:
    appSpec: 
      replicas: 1
    queSpec: 
      replicas: 1
  tenantName: 3scale
  wildcardDomain: 3scale.apps.CHANGEME.com
