apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: grafana
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: <tu_usuario_codificado_en_base64>
  GF_SECURITY_ADMIN_PASSWORD: <tu_contraseña_codificada_en_base
