{
 "title": "3scale / Apicast",
 "tags": [
  "3scale",
  "apicast"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "pcrm-3scale" },
   { "name": "env", "label": "environment", "query": "production,staging" },
   {
    "name": "pod",
    "query": "label_values(nginx_http_connections{namespace='$namespace', pod=~'apicast-$env.*'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP connections (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'apicast-$env.*'}[1m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "HTTP connections (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'$pod'}[1m])) by (pod,state)",
     "legendFormat": "{{pod}}: {{state}}"
    }
   ]
  },
  {
   "title": "HTTP status codes (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apicast_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'5.*'}[1m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(apicast_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'4.*'}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(apicast_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'3.*'}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(apicast_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'2.*'}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "HTTP status codes (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apicast_status{namespace='$namespace', pod=~'$pod', status=~'5.*'}[1m])",
     "legendFormat": "{{pod}}: 5XX"
    },
    {
     "expr": "rate(apicast_status{namespace='$namespace', pod=~'$pod', status=~'4.*'}[1m])",
     "legendFormat": "{{pod}}: 4XX"
    },
    {
     "expr": "rate(apicast_status{namespace='$namespace', pod=~'$pod', status=~'3.*'}[1m])",
     "legendFormat": "{{pod}}: 3XX"
    },
    {
     "expr": "rate(apicast_status{namespace='$namespace', pod=~'$pod', status=~'2.*'}[1m])",
     "legendFormat": "{{pod}}: 2XX"
    }
   ]
  },
  {
   "title": "Upstream status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(upstream_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'5.*'}[1m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'4.*'}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'3.*'}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace='$namespace', pod=~'apicast-$env.*', status=~'2.*'}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "errors / min (${pod})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_error_log{namespace='$namespace',pod=~'$pod', level=~'error|crit|alert|emerg'}[1m])",
     "legendFormat": "{{pod}}: {{level}}"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'apicast-$env.*', level=~'error|crit|alert|emerg'}[1h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 6h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'apicast-$env.*', level=~'error|crit|alert|emerg'}[6h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 12h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'apicast-$env.*', level=~'error|crit|alert|emerg'}[12h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'apicast-$env.*', level=~'error|crit|alert|emerg'}[24h]))"
    }
   ]
  },
  {
   "title": "3scale Backend calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(threescale_backend_calls{namespace='$namespace', pod=~'apicast-$env.*'}[1m])) by (endpoint, status)",
     "legendFormat": "{{endpoint}}: {{status}}"
    }
   ]
  },
  {
   "title": "Used shared dictionaries space ($pod)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "100 - (openresty_shdict_free_space{namespace='$namespace',pod='$pod'} / openresty_shdict_capacity{namespace='$namespace',pod='$pod'} * 100)",
     "legendFormat": "{{dict}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicationcontroller_status_ready_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicationcontroller_spec_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'}) - sum(kube_replicationcontroller_status_ready_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'apicast-$env.*'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'apicast-$env.*'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicationcontroller_spec_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'})",
     "legendFormat": "total-pods"
    },
    {
     "expr": "sum(kube_replicationcontroller_status_ready_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'})",
     "legendFormat": "avail-pods"
    },
    {
     "expr": "sum(kube_replicationcontroller_spec_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'}) - sum(kube_replicationcontroller_status_ready_replicas{namespace='$namespace',replicationcontroller=~'apicast-$env.*'})",
     "legendFormat": "unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'apicast-$env.*'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'apicast-$env.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'apicast-$env.*', container!=''}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'apicast-$env.*', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'apicast-$env.*', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'apicast-$env.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'apicast-$env.*', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace', pod=~'apicast-$env.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace', pod=~'apicast-$env.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}